Estimating model y
error inside ode() of model_ode_error.
params at error: [] Error message: lambdify() got an unexpected keyword argument 'args'
Excepted an error: lambdify() got an unexpected keyword argument 'args'!! 
Model: y
Estimating model x
error inside ode() of model_ode_error.
params at error: [] Error message: lambdify() got an unexpected keyword argument 'args'
Excepted an error: lambdify() got an unexpected keyword argument 'args'!! 
Model: x
Estimating model C0*y + x
error inside ode() of model_ode_error.
params at error: [-0.44688163] Error message: lambdify() got an unexpected keyword argument 'args'
Excepted an error: The map-like callable must be of the form f(func, iterable), returning a sequence of numbers the same length as 'iterable'!! 
Model: C0*y + x
Estimating model 2*x
error inside ode() of model_ode_error.
params at error: [] Error message: lambdify() got an unexpected keyword argument 'args'
Excepted an error: lambdify() got an unexpected keyword argument 'args'!! 
Model: 2*x
Estimating model 3*y
error inside ode() of model_ode_error.
params at error: [] Error message: lambdify() got an unexpected keyword argument 'args'
Excepted an error: lambdify() got an unexpected keyword argument 'args'!! 
Model: 3*y

 ModelBox: 5 models
-> y, p = 0.18, parse trees = 1, valid = False
-> x, p = 0.18, parse trees = 1, valid = False
-> C0*y + x, p = 0.0144, parse trees = 1, valid = False
-> 2*x, p = 0.0216, parse trees = 1, valid = False
-> 3*y, p = 0.0025920000000000006, parse trees = 1, valid = False 

Final score:
model: y                             ; error: 100000000      
model: x                             ; error: 100000000      
model: x - 3.65420054655066*y        ; error: 100000000      
model: 2*x                           ; error: 100000000      
model: 3*y                           ; error: 100000000      

 While dataset was generated by diff. eq. ẏ = 0.4·y + x   
